consumoconsciente/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include, re_path
from django.views.generic import TemplateView

urlpatterns = [
    path('ccprojetointegrador/admin/', admin.site.urls),
    path('',include('principal.urls')),
]

principal/urls.py
from django.urls import path, re_path
from . import views


app_name="principal"
urlpatterns = [
    path('', views.index, name='index'),
    path('calculadora/',views.calculadora, name="calculadora"),
    path('aprendaeconomizar/',views.aprendaeconomizar, name="aprendaeconomizar"),
    path('resultados/',views.resultados, name="resultados"),
    path('referencias/',views.referencias, name="referencias"),
    path('sobre/',views.sobre, name="sobre"),
    re_path(r'^.*/$', views.pagina_inexistente, name="paginaInexistente")
]

principal/models.py
from django.db import models

# Create your models here.

principal/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader

def index(request):
    return render(request=request,template_name="principal/index.html", context={"nome":"Início"})

def calculadora(request):
    return render(request=request,template_name="principal/calculadora.html", context={"nome":"Calculadora"})

def aprendaeconomizar(request):
    return render(request=request,template_name="principal/aprendaeconomizar.html", context={"nome":"Aprenda a Economizar"})

def resultados(request):
    return render(request=request,template_name="principal/resultados.html", context={"nome":"Resultados"})

def referencias(request):
    return render(request=request,template_name="principal/referencias.html", context={"nome":"Referências"})

def sobre(request):
    return render(request=request,template_name="principal/sobre.html", context={"nome":"Sobre"})

def pagina_inexistente(request):
    return render(request=request, template_name="principal/404.html", context={"nome":"404"})

principal/templates/principal/aprendaeconomizar.html
{% extends "./base.html" %}
{% load static %}

{% block linksadicionais %}
  <link rel='stylesheet' type='text/css' media='screen' href="{% static 'principal/css/aprendaeconomizar.css' %}"/>
{% endblock linksadicionais %}

{% block titulopagina %}
    <div class="container-xxl py-5 cor-fundo-3 hero-header mb-5 darkMode">
        <div class="container my-5 py-5 px-lg-5">
            <div class="row g-5 py-5">
                <div class="col-lg-6 text-center text-lg-start">
                    <h1 class="text-white mb-4 animated zoomIn">Aprenda a Economizar</h1>
                    <p class="text-white pb-3 animated zoomIn">A seguir, você encontrará alguns links com informações e dicas sobre economia de energia elétrica residencial.</p>
                </div>
                <div class="col-lg-6 text-center text-lg-start">
                    <img class="img-fluid img-titulo-pagina" src="{% static 'principal/img/aprender-economizar.svg' %}" alt="Aprenda a enconomizar">
                </div>
            </div>
        </div>
    </div>
{% endblock titulopagina %}


{% block corpo %}
    <div class="container my-5 py-5 px-lg-5">
        <p class="texto-E">Dicas de consumo:</p>
        <ul class="lista-links">
            <li><a href="https://www.enel.com.br/pt-saopaulo/Para_Voce/Dicas_e_Orientacoes.html> Acesso em 14/10/2021">Dicas e Orientacoes da Enel</a></li>
            <li><a href="http://www2.aneel.gov.br/arquivos/PDF/17-05_materia1_3.pdf">Material em pdf da Aneel</a></li>
            <li><a href="https://www.aneel.gov.br/busca?p_p_id=101&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_101_struts_action=%2Fasset_publisher%2Fview_content&_101_returnToFullPageURL=http%3A%2F%2Fwww.aneel.gov.br%2Fbusca%3Fp_auth%3DG1d8xWfJ%26p_p_id%3D3%26p_p_lifecycle%3D1%26p_p_state%3Dnormal%26p_p_state_rcv%3D1&_101_assetEntryId=14571137&_101_type=content&_101_groupId=656877&_101_urlTitle=aprenda-a-calcular-o-consumo-de-seu-aparelho-e-economize-energia&inheritRedirect=true">Aprenda a calcular o consumo de seu aparelho e economize energia</a></li>
            <li><a href="https://www.techtudo.com.br/dicas-e-tutoriais/noticia/2014/01/tvs-e-computadores-quem-gasta-mais-energia.html">TVs e Computadores: quem gasta mais energia?</a></li>
            <li><a href="https://www2.inmetro.gov.br/pbe/a_etiqueta.php">Etiqueta de eficiência energética</a></li>
            <li><a href="http://www.inmetro.gov.br/consumidor/tabelas.asp">Tabelas de consumo/eficiência energética </a></li>
        </ul>
        <p class="texto-E">Notícias sobre bandeira vermelha:</p>
        <ul class="lista-links">
            <li><a href="https://www.cnnbrasil.com.br/business/entenda-as-mudancas-na-sua-conta-de-luz-com-a-nova-bandeira-tarifaria/">Entenda as mudanças na sua conta de luz com a nova bandeira tarifária </a></li>
            <li><a href="https://agora.folha.uol.com.br/grana/2021/08/tarifa-da-bandeira-vermelha-vai-a-r-1420.shtml">Governo cria nova bandeira de R$ 14,20 na conta de luz</a></li>
        
        </ul>
    </div> 
    
{% endblock corpo %}

principal/templates/principal/calculadora.html
{% extends "./base.html" %}
{% load static %}

{% block linksadicionais %}
  <link rel='stylesheet' type='text/css' media='screen' href="{% static 'principal/css/calculadora.css' %}"/>
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
{% endblock linksadicionais %}
  
{% block titulopagina %}
    <div class="container-xxl py-5 cor-fundo-2 hero-header mb-5 darkMode">
        <div class="container my-5 py-5 px-lg-5">
            <div class="row g-5 py-5">
                <div class="col-lg-6 text-center text-lg-start">
                    <h1 class="text-white mb-4 animated zoomIn">Calculadora Energética</h1>
                    <p class="text-white pb-3 animated zoomIn">Descubra quanta energia é gasta em sua residência usando a calculadora abaixo.</p>
                </div>
                <div class="col-lg-6 text-center text-lg-start">
                    <img class="img-fluid img-titulo-pagina" src="{% static 'principal/img/calcular-gasto-energia.svg' %}" alt="Pessoas conscientes do consumo de energia">
                </div>
            </div>
        </div>
    </div>
{% endblock titulopagina %}

{% block corpo %}
  <div class="container my-5 py-5 px-lg-5">
    <h2 class="titulo-bloco-conteudo">Calcule aqui</h2>
        <p class="texto-D">
      Basta escolher o aparelho, aparecerá a potência média (pode ser alterada caso saiba a correta), colocar a quantidade do mesmo item, inserir as horas ou minutos de uso e os dias de consumo em um mês.
    </p>
  </div> 

  <div id="bloco-popup">
    <div id="bloco-new-item">
      <button id="bloco-fechar">X</button>
      <div id="bloco-info">
        <p class="label-inputs-pop">Nome do Aparelho</p>
        <input id="valorNomeAparelho" class="itens-atributes-pop input" name="nomeAparelho" type="text" list="lista-aparelhos" placeholder="Ex: Chuveiro" value="">
        <datalist id="lista-aparelhos">
        </datalist>
        <p class="label-inputs-pop">Potência (W)</p>
        <input id="valorPotencia" class="itens-atributes-pop zerar-valor input" name="potencia" type="number" min="0" placeholder="Ex: 5500" value="">
        <p class="label-inputs-pop">Quantidade</p>
        <input class="itens-atributes-pop zerar-valor input" name="quantidade" type="number" min="0" placeholder="Ex: 1" value="">
        <p class="label-inputs-pop">Tempo de Uso</p>
        <input class="itens-atributes-pop zerar-valor input" name="tempo" type="number" min="1" placeholder="Ex: 12" value="">
        <select class="itens-atributes-pop" name="aparelho">
          <option value="horasDia">horas/dia</option>
          <option value="minutosDia">minutos/dia</option>
        </select>
        <p class="label-inputs-pop">Dias</p>
        <input class="itens-atributes-pop resetar-dias input" name="dias" type="number" min="0" max="31" placeholder="Ex: 30" value="30">
        <button id="bloco-adicionar" >Adicionar</button>
      </div>
    </div>
  </div>

  <div class="bloco-itens-main container darkMode">
    <div class="bloco-itens-list">
      <div class="bloco-item-aparelho">
          <div class="aparelho-detalhe ">
            <p class="label-inputs">Nome do Aparelho</p>
            <p class="itens-atributes zerar-valor darkMode"></p>
          </div>
          <div class="aparelho-detalhe">
            <p class="label-inputs">Potência (W)</p>
            <p class="itens-atributes zerar-valor input darkMode"></p>
          </div>
          <div class="aparelho-detalhe">
            <p class="label-inputs">Quantidade</p>
            <p class="itens-atributes zerar-valor input darkMode"></p>
          </div>
          <div class="aparelho-detalhe">
            <p class="label-inputs">Tempo de Uso Diário</p>
            <p class="itens-atributes zerar-valor input darkMode"></p>
          </div>
          <div class="aparelho-detalhe">
            <p class="label-inputs">Dias</p>
            <p class="itens-atributes zerar-valor input darkMode"></p>
          </div>
          <div class="action-editar">
            <p>Editar</p>
          </div>
          <div class="action-delete">
            <p class="action-text">Excluir</p>
          </div>
      </div>
    </div>

    <div class="bloco-itens-actions">
      <div class="action-add"><p class="action-text">Adicionar Aparelho</p></div>
      <div class="action-calcular"><p class="action-text">Calcular</p></div>
    </div>

  </div>
  
  <div id="piechart"></div>
  <div id="tablechart"></div>

  <div class="bloco-valores-totais darkMode">
    <p class="label-valores-totais">Total (kWh)</p>
    <p>
      Consumo total simulado dos aparelhos inseridos na calculadora:
    </p>
    <input  id="total-kwh" class="valores-totais" name="potenciaTotal" placeholder="Consumo Total kWh" class="input"  value="" readonly>
      <hr class="linhas-divisorias" />
    <p class="label-valores-totais">Custo por kWh</p>
    <p>
      Como descobrir o custo por kWh:<br/>
      1- Localize na sua conta de energia o seu consumo em kWh<br/>
      2- Divida o valor total da sua conta pelo consumo<br/>
      3- Exemplo: R$ 268,56 / 340kWh = R$ 0,78 por kWh<br/>
      4- Insira o resultado abaixo:
    </p>
    <input  id="taxa-kwh" class="valores-totais" name="taxaPotencia" type="number" min="0" placeholder="0.78" class="input"  step="0.1" value="0.78">
    <hr class="linhas-divisorias" />
    <p class="label-valores-totais">Total (R$)</p>
    <p>O valor abaixo desconsidera impostos e tarifação por bandeira</p>
    <input  id="total-reais-gasto" class="valores-totais" name="valorTotal" placeholder="Gasto Total em Reais" class="input"  value="0" readonly >
  </div>

  <div class="container-xxl cor-fundo-2 newsletter my-5 wow fadeInUp darkMode" data-wow-delay="0.1s">
    <div class="container px-lg-5">
        <div class="row align-items-center" style="height: 250px;">
            <div class="col-12 col-md-6">
                <h3 class="text-white">Aprenda a Economizar</h3>
                <small class="text-white">Dicas sobre como economizar energia em diversos aparelhos.</small>
            </div>
            <div class="col-md-6 text-center">
                <a href="{% url 'principal:aprendaeconomizar' %}" class="btn btn-light py-sm-3 px-sm-5 rounded-pill me-3 animated slideInLeft">Clique aqui e aprenda a economizar</a>
            </div>
        </div>
    </div>
  </div>

  <div class="container my-5 py-5 px-lg-5">
    <h2 class="titulo-bloco-conteudo">Fórmula usada no cálculo de consumo de energia</h2>
    <p style="text-align: center;" class="texto-D">
      ( Potência em Watts / 1000) x Quantidade de itens x Dias por mês x Horas por dia = kWh dos itens
    </p>
    <h2 class="titulo-bloco-conteudo">Fórmula usada para encontrar potência de um aparelho</h2>
    <p style="text-align: center;" class="texto-D">
       Caso o aparelho não mostre a potência, use a fórmula abaixo: 
    </p>
    <p style="text-align: center;" class="texto-D">
      Ampere (A) x Voltagem (V) = Watts (W)
    </p>
  </div> 

{% endblock corpo %}
  
{% block scriptpagina %}
  <script type="text/javascript" src="{% static 'principal/js/calculadora.js' %}"></script>
{% endblock scriptpagina %}

principal/templates/principal/footer.html
<!-- Footer Start -->
<div class="container-fluid cor-fundo-1 text-light footer mt-5 pt-5 wow fadeIn darkMode" data-wow-delay="0.1s">
    <div class="container py-5 px-lg-5">
        <div class="row g-5">
            <div class="col-md-6 col-lg-6">
                <h5 class="text-white mb-4">Localização</h5>
                <p><i class="fa fa-map-marker-alt me-3"></i>Polo de Araçatuba</p>
                <p><i class="fa fa-map-marker-alt me-3"></i>Polo de Barueri</p>
                <p><i class="fa fa-map-marker-alt me-3"></i>Polo de São Paulo - Campo Limpo</p>
                <div class="d-flex pt-2">
                    <a class="btn btn-outline-light btn-social" href="#"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-outline-light btn-social" href="#"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-light btn-social" href="#"><i class="fab fa-youtube"></i></a>
                    <a class="btn btn-outline-light btn-social" href="#"><i class="fab fa-instagram"></i></a>
                    <a class="btn btn-outline-light btn-social" href="#"><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
            <div class="col-md-6 col-lg-6">
                <h5 class="text-white mb-4">Mais Informações</h5>
                <a class="btn btn-link" href="{% url 'principal:sobre' %}">Sobre nós</a>
            </div>
        </div>
    </div>
    <div class="container px-lg-5">
        <div class="copyright">
            <div class="row">
                <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                    &copy; <a class="border-bottom" href="#">Projeto Integrador II - UNIVESP - SP</a>
                    <a class="border-bottom" href="#">2022</a>
                </div>
                <div class="col-md-6 text-center text-md-end">
                    <div class="footer-menu">
                        <a href="{% url 'principal:index' %}">Início</a>
                        <a href="{% url 'principal:sobre' %}">Ajuda</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->

principal/templates/principal/index.html
{% extends "./base.html" %}
{% load static %}

{% block titulopagina %}
    <div class="container-xxl py-5 cor-fundo-1 hero-header mb-5 darkMode">
        <div class="container my-5 py-5 px-lg-5">
            <div class="row g-5 py-5">
                <div class="col-lg-6 text-center text-lg-start">
                    <h1 class="text-white mb-4 animated zoomIn">Bem Vindo ao Calculador de Energia Elétrica</h1>
                    <p class="text-white pb-3 animated zoomIn">Entenda melhor o seu consumo de energia e crie novos hábitos.</p>
                    <a href="{% url 'principal:calculadora' %}" class="btn btn-light py-sm-3 px-sm-5 rounded-pill me-3 animated slideInLeft">Simular Consumo</a>
                </div>
                <div class="col-lg-6 text-center text-lg-start">
                    <img class="img-fluid img-titulo-pagina" src="{% static 'principal/img/engenheiro-eletrico-com-lampada.svg' %}" alt="Engenheiro elétrico com lâmpada">
                </div>
            </div>
        </div>
    </div>
{% endblock titulopagina %}

{% block corpo %}

        <div class="container-xxl py-5">
            <div class="container px-lg-5">
                <div class="row g-5">
                    <div class="col-lg-12 wow fadeInUp" data-wow-delay="0.1s">
                        <div class="section-title position-relative mb-4 pb-2">
                            <h6 class="position-relative text-primary ps-4">Sobre</h6>
                            <h2 class="mt-2">Contexto</h2>
                        </div>
                        <div class="row g-5">
                            <div class="col-lg-6">
                                <img class="img-fluid wow zoomIn" data-wow-delay="0.5s" src="{% static 'principal/img/equipe-grafico-lousa.svg' %}" alt="Equipe analisando gráfico">
                            </div>
                            <div class="col-lg-6">
                                <p class="mb-4">Não é recente o apelo para que a população modifique seus hábitos relacionados ao consumo de energia elétrica, especialmente em épocas de estiagem.</p>
                                <p class="mb-4">Nos períodos de ausência de chuvas e consequente queda dos níveis dos reservatórios de água de todo o país, o risco de "apagões" se torna inevitável.</p>
                                <p class="mb-4">Além de fazer com o que o consumidor final precise arcar com cobranças extras nas tarifas de energia, o sistema elétrico corre o risco de sofrer interrupções generalizadas caso as pessoas não mudarem alguns hábitos.
                                    Dessa forma, torna-se clara a importância de reduz o uso desnecessário de alguns eletrodomésticos ou até mesmo evitar o uso de alguns aparelhos.</p>
                                <p class="mb-4">Devemos então limitar o uso desnecessário ou até mesmo evitar o uso de alguns aparelhos.</p>
                                <p class="mb-4">Neste site, você ter uma noção do quanto os seus aparelhos eletrônicos estão consumindo de energia e se programar para praticar a utilização consciente da energia elétrica em sua residência.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-xxl py-5">
            <div class="container px-lg-5">
                <div class="row g-5">
                    <div class="col-lg-12 wow fadeInUp" data-wow-delay="0.1s">
                        <div class="section-title position-relative mb-4 pb-2">
                            <h6 class="position-relative text-primary ps-4">Sobre</h6>
                            <h2 class="mt-2">A conta de energia</h2>
                        </div>
                        <div class="row g-5">
                            <div class="col-lg-6">
                                <p class="mb-4">Mudanças recentes fizeram o consumidor residencial se adaptar à nova realidade: aumento da conta de energia elétrica. Com o agravamento nas condições de geração de energia, a população passou a arcar com a tarifação de maior valor.</p>
                                <p class="mb-4">Assim sendo, este projeto é apresentado também com o objetivo de contribuir para a redução do valor monetário da conta mensal de energia elétrica.</p>
                            </div>
                            <div class="col-lg-4">
                                <img class="img-fluid wow zoomIn" data-wow-delay="0.5s" src="{% static 'principal/img/pessoa-calculando-conta.svg' %}" alt="Pessoa calculando conta de energia elétrica">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Início Bloco do botão para simular -->
        <div class="container-xxl cor-fundo-1 newsletter my-5 wow fadeInUp darkMode" data-wow-delay="0.1s">
            <div class="container px-lg-5">
                <div class="row align-items-center" style="height: 250px;">
                    <div class="col-12 col-md-6">
                        <h3 class="text-white">Simule seu Consumo de Energia</h3>
                        <small class="text-white">Escolha alguns eletrodomésticos e realize quantas simulações desejar clicando no botão ao lado.</small>
                    </div>
                    <div class="col-md-6 text-center">
                        <a href="{% url 'principal:calculadora' %}" class="btn btn-light py-sm-3 px-sm-5 rounded-pill me-3 animated slideInLeft">Simular Consumo</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Fim Bloco do botão para simular -->
       
{% endblock corpo %}

principal/templates/principal/menu.html
{% load static %}      
        
<!-- Navbar & Hero Start -->
<div class="container-xxl position-relative p-0">
    <nav class="navbar navbar-expand-lg navbar-light py-3 py-lg-0 darkMode">
        <div class="navbar-titulo navbar-brand p-0">
            <a href="{% url 'principal:index' %}">
                <img src="{% static 'principal/img/logo-principal.png' %}" alt="Logo Consumo Consciente">
            </a>
            <p>Consumo <br/> Consciente</p>
        </div>
        <button class="navbar-toggler whiteMode" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="fa fa-bars"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto py-0">
                <a href="{% url 'principal:index' %}" class="nav-item nav-link active">Início</a>
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle darkMode2" data-bs-toggle="dropdown">Informações</a>
                    <div class="dropdown-menu m-0">
                        <a href="{% url 'principal:resultados' %}" class="dropdown-item">Resultados</a>
                        <a href="{% url 'principal:aprendaeconomizar' %}" class="dropdown-item">Aprenda a Economizar</a>
                        <a href="{% url 'principal:referencias' %}" class="dropdown-item">Referências</a>
                    </div>
                </div>
                <a href="{% url 'principal:sobre' %}" class="nav-item nav-link darkMode2">Sobre</a>
            </div>
            <a href="{% url 'principal:calculadora' %}" class="btn btn-secondary text-light rounded-pill py-2 px-4 ms-3">Simular Consumo</a>
            <!--a href="#" class="btn rounded-pill py-2 px-2 ms-4 " id="alto-contraste" title="Ativar Alto-contraste"><i class="alto-contraste fa fa-adjust"></i><strong>Alto-contraste</strong></a-->
            <div class="btn rounded-pill py-2 px-2 ms-4">
                <input type="checkbox" class="checkboxDarkMode" id="alto-contraste"/>
                <label class="labelDarkMode" for="alto-contraste">
                    <i class="fa fa-moon"></i>
                    <i class="fa fa-sun"></i>
                    <div class="ballDarkMode"></div>
                </label>
            </div>
            <button class="btn rounded-pill py-2 px-2 ms-4 mudar-fonte" id="aumentar-fonte" title="Aumentar Fonte"><i></i><strong>A+</strong></button>
            <button class="btn rounded-pill py-2 px-2 ms-4 mudar-fonte" id="diminuir-fonte" title="Aumentar Fonte"><i></i><strong>A-</strong></button>
        </div>
    </nav>
</div>
<!-- Navbar & Hero End -->

principal/templates/principal/resultados.html
{% extends "./base.html" %}
{% load static %}

{% block linksadicionais %}
  <link rel='stylesheet' type='text/css' media='screen' href="{% static 'principal/css/resultados.css' %}"/>
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
{% endblock linksadicionais %}

{% block titulopagina %}
    <div class="container-xxl py-5 cor-fundo-4 hero-header mb-5 darkMode">
        <div class="container my-5 py-5 px-lg-5">
            <div class="row g-5 py-5">
                <div class="col-lg-6 text-center text-lg-start">
                    <h1 class="text-white mb-4 animated zoomIn">Resultados da Pesquisa</h1>
                    <p class="text-white pb-3 animated zoomIn">Acompanhe abaixo o resultado a primeira pesquisa do projeto, realizada no 2º semestre de 2021, que obteve alguns hábitos de consumo de 68 usuários residenciais.</p>
                </div>
                <div class="col-lg-6 text-center text-lg-start">
                    <img class="img-fluid img-titulo-pagina" src="{% static 'principal/img/aprender-economizar.svg' %}" alt="Aprenda a enconomizar">
                </div>
            </div>
        </div>
    </div>
{% endblock titulopagina %}

{% block corpo %}
    <div class="container my-5 py-5 px-lg-5">
        <div class="section-title position-relative mb-4 pb-2">
            <h6 class="position-relative text-primary ps-4">Dados</h6>
            <h2 class="mt-2">Resultados</h2>
        </div>
        <p class="texto-D">Quando questionado sobre o conhecimento dos gastos de energia pelos eletrodomésticos residenciais, obtivemos a seguinte resposta:</p>
        <div id="piechart" class="bloco-charts"></div>
        <p class="legenda-referencia">Fonte: Autoria Própria</p>
        <p class="texto-D">
            De acordo com as respostas apresentadas acima, em sua maioria, os respondentes não têm conhecimento dos gastos energéticos de seus eletrodomésticos.
        </p>
        <p class="texto-D">
            Questionados sobre o conhecimento do custo por hora de seus eletrodomésticos, a resposta foi a seguir:
        </p>

        <div id="piechart-2" class="bloco-charts"></div> 
        <p class="legenda-referencia">Fonte: Autoria Própria</p>  
        <p class="texto-D">
            Conforme observado no Gráfico 2, a grande maioria dos respondentes relataram desconhecer o custo por hora de seus eletrodomésticos.
        </p>
        <p class="texto-D">
            Quando questionados sobre os eletrodomésticos mais utilizados em suas residências, a resposta foi a que segue: 
        </p>
        <div id="piechart-3" class="bloco-charts"></div> 
        <p class="legenda-referencia">Fonte: Autoria Própria</p> 
        <p class="texto-D">
            Conforme mostrado acima, os eletrodomésticos de maior uso são, respectivamente, ventilador, ferro de passar e máquina de lavar.
        </p>
        <p class="texto-D"> 
            Ao perguntar qual dos eletrodomésticos mais comuns acreditam consumir mais energia, obtivemos a seguinte resposta:
        </p>
        <div id="piechart-4" class="bloco-charts"></div>
        <p class="legenda-referencia">Fonte: Autoria Própria</p> 
        <p class="texto-D">
            De acordo com o exposto no gráfico acima, os eletrodomésticos com maior consumo foram, respectivamente, televisão, máquina de lavar e notebook.
        </p>
        <p class="texto-D">
            Ao questionar sobre o conhecimento de algum site ou aplicativo que auxiliasse no controle do consumo de energia, obtivemos o que segue:
        </p>
        <div id="piechart-5" class="bloco-charts"></div>
        <p class="legenda-referencia">Fonte: Autoria Própria</p> 
        <p class="texto-D">
            Conforme apresentado acima, a grande maioria dos respondentes desconhece alguma ferramenta de auxílio do controle da energia elétrica.
        </p>
        <p class="texto-D">
            Questionado sobre a possibilidade de redução dos gastos na conta de energia acompanhando o consumo dos eletrodomésticos, a resposta foi a seguinte:
        </p>
        <div id="piechart-6" class="bloco-charts"></div>
        <p class="legenda-referencia">Fonte: Autoria Própria</p> 
        <p class="texto-D">
            Conforme observado acima, grande parte dos respondentes acredita ser possível reduzir os gastos com a conta de energia elétrica havendo a possibilidade de controle do consumo de energia dos eletrodomésticos. 
        </p>
        <p class="texto-D">
            Quando questionado sobre a possibilidade de acompanhar o consumo de energia e, como consequência, reduzir o valor da conta de energia elétrica com o auxílio de um site, obtivemos o que segue: 
        </p>
        <div id="piechart-7" class="bloco-charts"></div>
        <p class="legenda-referencia">Fonte: Autoria Própria</p> 
        <p class="texto-D">
            Como visto no Gráfico 7, a maioria dos respondentes confirmaram que utilizariam um site que os permitisse acompanhar o consumo de seus eletrodomésticos e, consequentemente, possibilitasse a redução do gasto na conta de energia. 
        </p>
        </div> 
    
{% endblock corpo %}
{% block scriptpagina %}
  <script type="text/javascript" src="{% static 'principal/js/resultados.js' %}"></script>
{% endblock scriptpagina %}